
# Dependencies
markdown:       kramdown
redcarpet:
#extensions: ['smart']

highlighter:         rouge
fenced_code_blocks:  true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title: CREU Blog 2017 - 2018
description: Research of JN Matthews
tagline: Research of JN Matthews
url:         https://jenni-niels.github.io/CREU_blog/
paginate:            5
baseurl:     https://jenni-niels.github.io/CREU_blog/

# about
author:
  name: JN Matthews
